# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc88bf1331ddd569fa1be4b045234fc6e2cecb96f0db69e5b7ea9a5f98c0ae2fbbef1e3e30cb844407bd6bdf1a7ef36c3d10ac012ad15363ffdb1cdce4699403

test:
  secret_key_base: 5d50347b8b6154f9f1a6c2c0dcccfab76b95c27376decede3cdeee2995d5accd43c1ec0a18ba0c705314d053e01d1379ba99e214de401a3fd6d27cb8321666d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
